services:
  database:
      container_name: database
      image: postgres:16
      restart: unless-stopped
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
      volumes:
        - postgresql:/var/lib/postgresql/data
      ports:
        - 5432:5432
  application:
    image: guild-hub:0.1.0
    build:
      context: .
      dockerfile: src/GuildHub.Api/Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - database
volumes:
  postgresql:
